### ISSUE TITLE
Compile time error, help me ,please

### ISSUE THREAD

**Issue by LuckyFishGeek** [gbarbarov/led-race#1]
Arduino: 1.8.10 Hourly Build 2019/05/21 09:33 (Windows 7), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

C:\Users\Administrator\Desktop\arduino-nightly\arduino-builder -dump-prefs -logger=machine -hardware C:\Users\Administrator\Desktop\arduino-nightly\hardware -tools C:\Users\Administrator\Desktop\arduino-nightly\tools-builder -tools C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -built-in-libraries C:\Users\Administrator\Desktop\arduino-nightly\libraries -libraries C:\Users\Administrator\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328old -vid-pid=1A86_7523 -ide-version=10810 -build-path C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_662228 -warnings=none -build-cache C:\Users\ADMINI~1\AppData\Local\Temp\arduino_cache_727188 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -verbose C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino
C:\Users\Administrator\Desktop\arduino-nightly\arduino-builder -compile -logger=machine -hardware C:\Users\Administrator\Desktop\arduino-nightly\hardware -tools C:\Users\Administrator\Desktop\arduino-nightly\tools-builder -tools C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -built-in-libraries C:\Users\Administrator\Desktop\arduino-nightly\libraries -libraries C:\Users\Administrator\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328old -vid-pid=1A86_7523 -ide-version=10810 -build-path C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_662228 -warnings=none -build-cache C:\Users\ADMINI~1\AppData\Local\Temp\arduino_cache_727188 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Users\Administrator\Desktop\arduino-nightly\hardware\tools\avr -verbose C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino
Using board 'nano' from platform in folder: C:\Users\Administrator\Desktop\arduino-nightly\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Users\Administrator\Desktop\arduino-nightly\hardware\arduino\avr
Detecting libraries used...
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\sketch\\led_race3_5_AD19_SMS.ino.cpp" -o nul
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\sketch\\led_race3_5_AD19_SMS.ino.cpp" -o nul
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel" "C:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel\\Adafruit_NeoPixel.cpp" -o nul
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel" "C:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel\\esp8266.c" -o nul
Generating function prototypes...
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\sketch\\led_race3_5_AD19_SMS.ino.cpp" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Users\\Administrator\\Desktop\\arduino-nightly\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\Administrator\\Documents\\Arduino\\libraries\\Adafruit_NeoPixel" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\sketch\\led_race3_5_AD19_SMS.ino.cpp" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\arduino_build_662228\\sketch\\led_race3_5_AD19_SMS.ino.cpp.o"
led_race1:19:7: error: redefinition of 'float speed1'

 float speed1=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:51:7: note: 'float speed1' previously defined here

 float speed1=0;

       ^

led_race1:20:7: error: redefinition of 'float speed2'

 float speed2=1.25;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:52:7: note: 'float speed2' previously defined here

 float speed2=0;

       ^

led_race1:21:7: error: redefinition of 'float dist1'

 float dist1=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:53:7: note: 'float dist1' previously defined here

 float dist1=0;

       ^

led_race1:22:7: error: redefinition of 'float dist2'

 float dist2=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:54:7: note: 'float dist2' previously defined here

 float dist2=0;

       ^

led_race1:24:6: error: redefinition of 'byte loop1'

 byte loop1=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:56:6: note: 'byte loop1' previously defined here

 byte loop1=0;

      ^

led_race1:25:6: error: redefinition of 'byte loop2'

 byte loop2=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:57:6: note: 'byte loop2' previously defined here

 byte loop2=0;

      ^

led_race1:27:6: error: redefinition of 'byte loop_max'

 byte loop_max=5;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:60:6: note: 'byte loop_max' previously defined here

 byte loop_max=5; //total laps race

      ^

led_race1:29:5: error: redefinition of 'int NPIXELS'

 int NPIXELS=300;

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:36:5: note: 'int NPIXELS' previously defined here

 int NPIXELS=MAXLED; // leds on track

     ^

led_race1:30:7: error: redefinition of 'float ACEL'

 float ACEL=0.2;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:63:7: note: 'float ACEL' previously defined here

 float ACEL=0.2;

       ^

led_race1:32:7: error: redefinition of 'float kf'

 float kf=1.5;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:64:7: note: 'float kf' previously defined here

 float kf=0.015; //friction constant

       ^

led_race1:34:6: error: redefinition of 'byte flag_sw1'

 byte flag_sw1=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:67:6: note: 'byte flag_sw1' previously defined here

 byte flag_sw1=0;

      ^

led_race1:35:6: error: redefinition of 'byte flag_sw2'

 byte flag_sw2=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:68:6: note: 'byte flag_sw2' previously defined here

 byte flag_sw2=0;

      ^

led_race1:38:19: error: redefinition of 'Adafruit_NeoPixel track'

 Adafruit_NeoPixel track = Adafruit_NeoPixel(NPIXELS, PIN_LED, NEO_GRB + NEO_KHZ800);

                   ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:73:19: note: 'Adafruit_NeoPixel track' previously declared here

 Adafruit_NeoPixel track = Adafruit_NeoPixel(MAXLED, PIN_LED, NEO_GRB + NEO_KHZ800);

                   ^

led_race1:40:5: error: redefinition of 'int tdelay'

 int tdelay = 5; 

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:75:5: note: 'int tdelay' previously defined here

 int tdelay = 5; 

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race1.ino: In function 'void setup()':

led_race1:42:6: error: redefinition of 'void setup()'

 void setup() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:90:6: note: 'void setup()' previously defined here

 void setup() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race1.ino: In function 'void loop()':

led_race1:55:6: error: redefinition of 'void loop()'

 void loop() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:242:6: note: 'void loop()' previously defined here

 void loop() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: At global scope:

led_race2:25:15: error: redefinition of 'int win_music []'

 int win_music[] = {

               ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:41:5: note: 'int win_music [9]' previously defined here

 int win_music[] = {

     ^

led_race2:32:5: error: redefinition of 'int TBEEP'

 int TBEEP=4; 

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:49:5: note: 'int TBEEP' previously defined here

 int TBEEP=3; 

     ^

led_race2:34:7: error: redefinition of 'float speed1'

 float speed1=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:51:7: note: 'float speed1' previously defined here

 float speed1=0;

       ^

led_race2:35:7: error: redefinition of 'float speed2'

 float speed2=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:52:7: note: 'float speed2' previously defined here

 float speed2=0;

       ^

led_race2:36:7: error: redefinition of 'float dist1'

 float dist1=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:53:7: note: 'float dist1' previously defined here

 float dist1=0;

       ^

led_race2:37:7: error: redefinition of 'float dist2'

 float dist2=0;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:54:7: note: 'float dist2' previously defined here

 float dist2=0;

       ^

led_race2:39:6: error: redefinition of 'byte loop1'

 byte loop1=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:56:6: note: 'byte loop1' previously defined here

 byte loop1=0;

      ^

led_race2:40:6: error: redefinition of 'byte loop2'

 byte loop2=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:57:6: note: 'byte loop2' previously defined here

 byte loop2=0;

      ^

led_race2:42:6: error: redefinition of 'byte leader'

 byte leader=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:59:6: note: 'byte leader' previously defined here

 byte leader=0;

      ^

led_race2:43:6: error: redefinition of 'byte loop_max'

 byte loop_max=5;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:60:6: note: 'byte loop_max' previously defined here

 byte loop_max=5; //total laps race

      ^

led_race2:45:5: error: redefinition of 'int NPIXELS'

 int NPIXELS=300;

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:36:5: note: 'int NPIXELS' previously defined here

 int NPIXELS=MAXLED; // leds on track

     ^

led_race2:46:7: error: redefinition of 'float ACEL'

 float ACEL=0.2;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:63:7: note: 'float ACEL' previously defined here

 float ACEL=0.2;

       ^

led_race2:47:7: error: redefinition of 'float FRICTION'

 float FRICTION=0.01;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race1.ino:31:7: note: 'float FRICTION' previously defined here

 float FRICTION=0.01;

       ^

led_race2:48:7: error: redefinition of 'float kf'

 float kf=1.5;

       ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:64:7: note: 'float kf' previously defined here

 float kf=0.015; //friction constant

       ^

led_race2:50:6: error: redefinition of 'byte flag_sw1'

 byte flag_sw1=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:67:6: note: 'byte flag_sw1' previously defined here

 byte flag_sw1=0;

      ^

led_race2:51:6: error: redefinition of 'byte flag_sw2'

 byte flag_sw2=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:68:6: note: 'byte flag_sw2' previously defined here

 byte flag_sw2=0;

      ^

led_race2:52:6: error: redefinition of 'byte draworder'

 byte draworder=0;

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:69:6: note: 'byte draworder' previously defined here

 byte draworder=0;

      ^

led_race2:54:15: error: redefinition of 'long unsigned int timestamp'

 unsigned long timestamp=0;

               ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:71:15: note: 'long unsigned int timestamp' previously defined here

 unsigned long timestamp=0;

               ^

led_race2:56:19: error: redefinition of 'Adafruit_NeoPixel track'

 Adafruit_NeoPixel track = Adafruit_NeoPixel(NPIXELS, PIN_LED, NEO_GRB + NEO_KHZ800);

                   ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:73:19: note: 'Adafruit_NeoPixel track' previously declared here

 Adafruit_NeoPixel track = Adafruit_NeoPixel(MAXLED, PIN_LED, NEO_GRB + NEO_KHZ800);

                   ^

led_race2:58:5: error: redefinition of 'int tdelay'

 int tdelay = 5; 

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:75:5: note: 'int tdelay' previously defined here

 int tdelay = 5; 

     ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void setup()':

led_race2:60:6: error: redefinition of 'void setup()'

 void setup() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:90:6: note: 'void setup()' previously defined here

 void setup() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void start_race()':

led_race2:67:6: error: redefinition of 'void start_race()'

 void start_race(){for(int i=0;i<NPIXELS;i++){track.setPixelColor(i, track.Color(0,0,0));};

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:105:6: note: 'void start_race()' previously defined here

 void start_race(){for(int i=0;i<NPIXELS;i++){track.setPixelColor(i, track.Color(0,0,0));};

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void winner_fx()':

led_race2:95:6: error: redefinition of 'void winner_fx()'

 void winner_fx() {/*for(int i=0;i<6;i++){tone(PIN_AUDIO,400+i*100);

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:133:6: note: 'void winner_fx()' previously defined here

 void winner_fx() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void burning1()':

led_race2:114:6: error: redefinition of 'void burning1()'

 void burning1(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:145:6: note: 'void burning1()' previously defined here

 void burning1(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void burning2()':

led_race2:118:6: error: redefinition of 'void burning2()'

 void burning2(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:149:6: note: 'void burning2()' previously defined here

 void burning2(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void track_rain_fx()':

led_race2:122:6: error: redefinition of 'void track_rain_fx()'

 void track_rain_fx(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:153:6: note: 'void track_rain_fx()' previously defined here

 void track_rain_fx(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void track_oil_fx()':

led_race2:126:6: error: redefinition of 'void track_oil_fx()'

 void track_oil_fx(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:157:6: note: 'void track_oil_fx()' previously defined here

 void track_oil_fx(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void draw_safety_car()':

led_race2:130:6: error: redefinition of 'void draw_safety_car()'

 void draw_safety_car(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:190:6: note: 'void draw_safety_car()' previously defined here

 void draw_safety_car(){

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void draw_car1()':

led_race2:134:6: error: redefinition of 'void draw_car1()'

 void draw_car1(void){for(int i=0;i<=loop1;i++){track.setPixelColor(((word)dist1 % NPIXELS)+i, track.Color(0,255-i*50,0));};   //i not see FX dimmer light ? Why ???                 

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:236:6: note: 'void draw_car1()' previously defined here

 void draw_car1(void){for(int i=0;i<=loop1;i++){track.setPixelColor(((word)dist1 % NPIXELS)+i, track.Color(0,255-i*20,0));};                   

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void draw_car2()':

led_race2:137:6: error: redefinition of 'void draw_car2()'

 void draw_car2(void){for(int i=0;i<=loop2;i++){track.setPixelColor(((word)dist2 % NPIXELS)+i, track.Color(255-i*50,0,0));};            

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:239:6: note: 'void draw_car2()' previously defined here

 void draw_car2(void){for(int i=0;i<=loop2;i++){track.setPixelColor(((word)dist2 % NPIXELS)+i, track.Color(255-i*20,0,0));};            

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race2.ino: In function 'void loop()':

led_race2:140:6: error: redefinition of 'void loop()'

 void loop() {

      ^

C:\Users\Administrator\Desktop\led-race-master\led_race3_5_AD19_SMS\led_race3_5_AD19_SMS.ino:242:6: note: 'void loop()' previously defined here

 void loop() {

      ^

Using library Adafruit_NeoPixel at version 1.2.3 in folder: C:\Users\Administrator\Documents\Arduino\libraries\Adafruit_NeoPixel 
exit status 1
redefinition of 'float speed1'
![20190606_190844](https://user-images.githubusercontent.com/29472751/59028666-aebf0a80-888e-11e9-846a-c6321930ea21.png)

**Comment by gbarbarov** [comment]
You need quit aditional .ino  of tabs,   i now deleting this olds version of folder

**Comment by LuckyFishGeek** [comment]
@gbarbarov  thank you very much！    good lucky every day
